### ISSUE TITLE
Blank page in Firefox

### ISSUE THREAD

**Issue by xuv** [snorpey/jpg-glitch#11]
Nothing is displayed.
The error in the console shows:
```NS_ERROR_UNEXPECTED:  jpg-glitch:1:0```

**Comment by snorpey** [comment]
hey @xuv thank you for taking the time to report this bug. unfortunately i'm having a hard time reproducing this bug.

could you help me out and provide some details?

* which operating system were you using?
* which version of firefox were you using?
* does this bug occur if you reload the page?
* were you on a mobile connection or a wifi?

thank you!

**Comment by xuv** [comment]
Hey @snorpey 
Sorry. My fault. I must have some weird addon to Firefox that blocked something. It works in Privacy mode. So now worries. Excellent work. Love it. And thanks for your reply.
