### ISSUE TITLE
A little translate issue

### ISSUE THREAD

**Issue by STRIXVERDEN** [snorpey/jpg-glitch#12]
This is not important but on the russian noun that means control it is written in the plural.
"УПРАВЛЕНИЯ" - wrong
"УПРАВЛЕНИЕ" - good
![capture](https://cloud.githubusercontent.com/assets/16992481/15983944/7d3e6968-2fc9-11e6-84e4-577b933e5d73.PNG)

**Comment by snorpey** [comment]
hey @STRIXVERDEN thank you for reporting this issue. i don't rpeak russian myself, so thank you for helping me out.

i fixed this issue in this commit d9b84bd064378cfc278cec6864ddd119d472eac4

thanks again!
