### ISSUE TITLE
Errors after compiling the production build

### ISSUE THREAD

**Issue by martindavies** [snorpey/jpg-glitch#18]
Hey, 

After building the production version there are a lot of problems with missing files and incorrect paths. Is there anything that needs amending in the scripts?

Thanks for the project by the way!

Thanks,

**Comment by snorpey** [comment]
hey @martindavies thank you for reporting this bug!

could you help me and provide a little bit more information, so i can get a better picture about what went wrong:

* can you describe the steps you took to arrive at the error message?
* what exactly does the error message say?
* do the errors show up in the browser console or in your terminal?

thank you!

**Comment by martindavies** [comment]
Yes of course – 

After running the build and running the app from the production folder the console throws up 

`Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8888/jpg-glitch-master/production/modules/images/icon/fullscreen.svg Failed to load resource: the server responded with a status of 404 (Not Found)
undefined:1 Uncaught (in promise) DOMException: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.
http://localhost:8888/jpg-glitch-master/production/images/icon/chevron-down.svg Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8888/jpg-glitch-master/production/glitchworker.min.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8888/jpg-glitch-master/lib/localforage.nopromises.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8888/jpg-glitch-master/lib/localforage.nopromises.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8888/jpg-glitch-master/lib/localforage.nopromises.js Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8888/jpg-glitch-master/lib/localforage.nopromises.js Failed to load resource: the server responded with a status of 404 (Not Found)
settingsworker.min.js:1 Uncaught [object DOMException]
storageworker.min.js:1 Uncaught [object DOMException]`

I can see the workspace fine but obviously the glitcher isn't working :(

Thanks!

**Comment by snorpey** [comment]
hey @martindavies,

thank you for reporting back!

for some reason, i can't seem to reproduce this issue on my machine. would you mind answering a few more questions?

which browser and operating system are you using?

the other day I added another update to make the build process a little bit easier to run, so i'm wondering if you could try to download the latest version and run the build script again? 

you can download the latest version [here](https://github.com/snorpey/jpg-glitch/archive/master.zip). then try opening the `jpg-glitch-master` folder in your terminal and run `npm install`, and after that `npm run build`.

does the build script work or are there any errors showing up in the terminal?

if the build script works could you post the contents of the `production` folder? here is what it should look like: [production.zip](https://github.com/snorpey/jpg-glitch/files/450360/production.zip)

sorry for asking all these questions. i'm just trying to figure out where i can improve the code...
thanks again for getting back to me!

**Comment by martindavies** [comment]
Hey, 

It looks like the update you have made works! After running npm build, everything is in the production folder and no errors in the console. I've made a few amends to the code and rerun the build and everything works fine. 

Thanks!

**Comment by snorpey** [comment]
sure thing. glad to see it works for you!
